name: readify_agi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - fastapi>=0.100.0
    - uvicorn
    - sqlalchemy<2.0.0
    - aiomysql
    - python-dotenv
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - starlette>=0.27.0
    - typing-extensions>=4.5.0
    - email-validator>=2.0.0
    - cryptography
    - llama-parse
    - langchain>=0.1.5
    - langchain-core>=0.1.14
    - langchain-community>=0.1.5
    - langchain-openai>=0.1.7
    - chromadb
    - openai>=1.3.0
    - tiktoken
    - agently>=0.4.0
    - pytest>=7.0.0
    - httpx>=0.24.0
    - pytest-asyncio>=0.21.0
    - python-multipart  # 用于文件上传
    - pypdf  # 用于PDF处理
    - google-search-results  # SerpAPI 库
 